name: Add to conda-forge

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: PyPi package name

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.0.1
      - name: Clone staged-reciped
        run: |
          git clone https://github.com/conda-forge/staged-recipes
      - name: Install grayskull
        run: |
          conda install -c conda-forge grayskull
      - name: Generate recipe for package using grayskull
        run: |
          grayskull pypi ${{ github.event.inputs.name }}
          ls -ltrh
          ls ${{ github.event.inputs.name }}/meta.yaml
      - name: Move recipe to staged recipe
        run: |
          cp ${{ github.event.inputs.name }} staged-recipes/recipes/ -r
          ls staged-recipes/recipes/
      - name: Commit Recipe
        run: |
          cd staged-recipes
          git add .
          git status
          git config --global user.email "dtu.amit@gmail.com"
          git config --global user.name "Amit Kumar"
          git commit -m "Add recipe for ${{ github.event.inputs.name }}"
      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.17
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Add Fork remote
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd staged-recipes
          git remote -v
          url=https://aktech:$GH_TOKEN@github.com/aktech/staged-recipes.git
          git remote add fork $url
          git remote -v
                
      - name: Push recipe to the fork branch
        run: |
          cd staged-recipes
          echo "Pushing recipe"
          git checkout -b ${{ github.event.inputs.name }}-$GITHUB_SHA
          git push fork
    
      - name: Create a PR on conda-forge
        run: |
          echo "TODO: Create a PR on conda-forge"
